{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "2814d70d-65eb-4dec-8d15-c754ccb10211",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-03-22 12:38:43.320 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-22 12:38:46.735 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\Users\\bhavy\\anaconda3\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2026-03-22 12:38:46.738 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-22 12:38:46.741 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-22 12:38:46.745 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-22 12:38:46.748 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-22 12:38:46.753 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-22 12:38:55.243 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-22 12:38:55.245 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-22 12:38:55.247 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-22 12:38:55.251 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-22 12:38:55.253 Session state does not function when running a script without `streamlit run`\n",
      "2026-03-22 12:38:55.258 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-22 12:38:55.261 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-22 12:38:55.265 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-22 12:38:55.269 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-22 12:38:55.276 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-22 12:38:55.281 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-22 12:38:55.285 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-22 12:38:55.288 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-03-22 12:38:55.292 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import string\n",
    "\n",
    "from sklearn.feature_extraction.text import TfidfVectorizer\n",
    "from sklearn.metrics.pairwise import cosine_similarity\n",
    "\n",
    "# Title\n",
    "st.title(\"AI Resume Screening System\")\n",
    "\n",
    "st.write(\"Upload a job description and rank resumes based on relevance.\")\n",
    "\n",
    "# Load dataset\n",
    "df = pd.read_csv(\"Resume.csv\")\n",
    "\n",
    "# Make sure column exists\n",
    "df['Resume_str'] = df['Resume_str'].astype(str)\n",
    "\n",
    "# Text cleaning\n",
    "def clean_text(text):\n",
    "    text = text.lower()\n",
    "    text = text.translate(str.maketrans('', '', string.punctuation))\n",
    "    return text\n",
    "\n",
    "df['clean_resume'] = df['Resume_str'].apply(clean_text)\n",
    "\n",
    "# Input job description\n",
    "job_description = st.text_area(\"Enter Job Description\")\n",
    "\n",
    "if st.button(\"Analyze Resumes\"):\n",
    "    if job_description.strip() == \"\":\n",
    "        st.warning(\"Please enter a job description\")\n",
    "    else:\n",
    "        job_clean = clean_text(job_description)\n",
    "\n",
    "        # Combine resumes + job\n",
    "        all_text = df['clean_resume'].tolist() + [job_clean]\n",
    "\n",
    "        # TF-IDF\n",
    "        vectorizer = TfidfVectorizer()\n",
    "        vectors = vectorizer.fit_transform(all_text)\n",
    "\n",
    "        # Similarity\n",
    "        similarity = cosine_similarity(vectors[:-1], vectors[-1])\n",
    "\n",
    "        df['match_score'] = similarity\n",
    "\n",
    "        # Rank\n",
    "        df_ranked = df.sort_values(by='match_score', ascending=False)\n",
    "\n",
    "        # Display\n",
    "        st.subheader(\"Top Candidates\")\n",
    "        st.dataframe(df_ranked[['Resume_str', 'match_score']].head(5))\n",
    "    \n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
